application: homepage
version: 1
runtime: php55
api_version: 1

handlers:
- url: /enjs.js
  static_files: vendor/phoxy/enjs/enjs.js
  upload: vendor/phoxy/enjs/enjs.js

- url: /(.+\.(css|js|ejs))$
  static_files: \1
  upload: .+\.(css|js|ejs)$

- url: /.*
  script: engine/coldstart.php

skip_files:
- .git.*
